portal/portal/urls.py
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.urls import path
from django.contrib import admin
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studio/', include('studio.urls')),
    path('', RedirectView.as_view(url='/studio/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/studio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('myorders/', views.LoanedOrdersByUserListView.as_view(), name='my-order'),
    path('myorders/<int:pk>', views.OrderDetailView.as_view(), name='order-detail'),
    path(r'customer/', views.LoanedOrdersAllListView.as_view(), name='all-order'),
    path('order/create/', views.OrderCreate.as_view(), name='order-create'),
    path('myorders/<int:pk>/update/', views.OrderUpdate.as_view(), name='order-update'),
    path('myorders/<int:pk>/delete/', views.OrderUserDelete.as_view(), name='order-delete'),
    path('myorders/<int:pk>/delete/', views.OrderAdminDelete.as_view(), name='order-delete'),
]

portal/studio/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.core.validators import FileExtensionValidator
from django.core.validators import RegexValidator


# Create your models here.


class User(AbstractUser):
    name = models.CharField(max_length=200, verbose_name='Имя', blank=False, validators=[
        RegexValidator(
            regex='^[А-Яа-я -]*$',
            message='Имя пользователя должно состоять из кириллицы',
            code='invalid_username'
        ),
    ])
    surname = models.CharField(max_length=200, verbose_name='Фамилия', blank=False, validators=[
        RegexValidator(
            regex='^[А-Яа-я -]*$',
            message='Фамилия пользователя должно состоять из кириллицы',
            code='invalid_username'
        ),
    ])
    patronymic = models.CharField(max_length=200, verbose_name='Отчество', blank=True, validators=[
        RegexValidator(
            regex='^[А-Яа-я -]*$',
            message='Отчество пользователя должно состоять из кириллицы',
            code='invalid_username'
        ),
    ])
    username = models.CharField(max_length=200, verbose_name='Логин', unique=True, blank=False, validators=[
        RegexValidator(
            regex='^[A-Za-z -]*$',
            message='Имя пользователя должно состоять только из латиницы',
            code='invalid_username'
        ),
    ])
    email = models.EmailField(max_length=200, verbose_name='Почта', unique=True, blank=False)
    password = models.CharField(max_length=200, verbose_name='Пароль', blank=False)
    role = models.CharField(max_length=200, verbose_name='Роль',
                            choices=(('admin', 'Администратор'), ('user', 'Пользователь')), default='user')
    USERNAME_FIELD = 'username'

    def __str__(self):
        return str(self.name) + ' ' + str(self.surname)

    class Meta:
        ordering = ['name']


def get_name_file(instance, filename):
    return 'portal/file'.join([get_random_string(5) + '_' + filename])


class Category(models.Model):
    name = models.CharField(max_length=200, help_text="Укажите категорию")

    def __str__(self):
        return self.name


class Order(models.Model):
    day_add = models.DateField(null=True, blank=True)
    name = models.CharField(max_length=200, verbose_name='Имя', blank=False)
    summary = models.TextField(max_length=1000, help_text="Описание", blank=False)
    category = models.ForeignKey('category', help_text="Выбор категории", on_delete=models.CASCADE, blank=False)
    photo_file = models.ImageField(max_length=200, upload_to=get_name_file, blank=False, null=True,
                                   validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    customer_order = models.ForeignKey('user', on_delete=models.SET_NULL, null=True, blank=True)
    comment = models.TextField(max_length=1000, help_text="Комментарий", blank=True)
    img = models.ImageField(max_length=200, upload_to=get_name_file, blank=True, null=True,
                                   validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    LOAN_STATUS = (
        ('n', 'Новая'),
        ('a', 'Принято в работу'),
        ('c', 'Выполнено'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='n')

    def get_status_name(self):
        for status in self.LOAN_STATUS:
            if status[0] == self.status:
                return status[1]
        return 'Не задан'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

    class Meta:
        ordering = ["status"]
        permissions = (("can_mark_returned", "Установите статус заказа"),)


user_registrated = Signal()

portal/studio/forms.py
from django import forms
from django.contrib.messages import debug
from django.core.exceptions import ValidationError
from django.forms import TextInput

from .models import User, Order
from .models import user_registrated


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput, )
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз')

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',
                  'name', 'surname', 'patronymic')


class UpdateOrderForm(forms.ModelForm):
    LOAN_STATUS = (
        ('n', 'Новая'),
        ('a', 'Принято в работу'),
        ('c', 'Выполнено'),
    )
    status = forms.ChoiceField(label='Статус заявки', help_text='Статус', widget=forms.Select, choices=LOAN_STATUS)
    img = forms.ImageField(label='Фото работы', required=False)
    comment = forms.CharField(label='Комментарий', required=False, help_text='Комментарий')

    def clean(self):
        super().clean()
        print(self.cleaned_data)

        status = self.cleaned_data.get('status')
        comment = self.cleaned_data.get('comment')
        img = self.cleaned_data.get('img')
        if status == 'a' and comment == '':
            errors = {'status': ValidationError(
                'После изменения статуса на принят в работу нужно добавить комментарий'
            )}
            raise ValidationError(errors)

            raise ValidationError(errors)
        elif status == 'n':
            errors = {'status': ValidationError(
                'Вы не можете изменить статус на новый'
            )}
            raise ValidationError(errors)

    class Meta:
        model = Order
        fields = ('status', 'img', 'comment')

portal/studio/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from .forms import RegisterUserForm, UpdateOrderForm
from django.urls import reverse_lazy
from .models import User, Order
from django.views.generic.base import TemplateView
from django.views import generic
import datetime


# Create your views here.


def index(request):
    this_month = datetime.datetime.now().month
    num_order = Order.objects.filter(status__exact='c').filter(day_add__month=this_month)[:4]
    num_status = Order.objects.filter(status__exact='n').count()
    return render(
        request,
        'index.html',
        context={'num_order': num_order, 'num_status': num_status},
    )


class OrderDetailView(generic.DetailView):
    model = Order


class LoanedOrdersByUserListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'studio/order_list_customer_user.html'
    paginate_by = 10
    status = None

    def get(self, request, *args, **kwargs):
        # print(request.GET.get('status'))
        if request.GET.get('status'):
            self.status = request.GET.get('status')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
        context = super(LoanedOrdersByUserListView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и инициализируем её некоторым значением
        context['status_list'] = Order.LOAN_STATUS
        # print(Order.LOAN_STATUS)
        return context

    def get_queryset(self):
        if self.status:
            return Order.objects.filter(customer_order=self.request.user, status=self.status)
        return Order.objects.filter(customer_order=self.request.user).order_by('-day_add')


class LoanedOrdersAllListView(PermissionRequiredMixin, generic.ListView):
    model = Order
    permission_required = 'studio.can_mark_returned'
    template_name = 'studio/order_list_customer_all.html'
    paginate_by = 10
    status = None

    def get(self, request, *args, **kwargs):
        # print(request.GET.get('status'))
        if request.GET.get('status'):
            self.status = request.GET.get('status')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
        context = super(LoanedOrdersAllListView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и инициализируем её некоторым значением
        context['status_list'] = Order.LOAN_STATUS
        # print(Order.LOAN_STATUS)
        return context

    def get_queryset(self):
        return Order.objects.all()


class OrderCreate(CreateView):
    model = Order
    fields = ['name', 'summary', 'category', 'photo_file']

    def form_valid(self, form):
        form.instance.customer_order = self.request.user
        form.instance.day_add = datetime.date.today()
        return super().form_valid(form)


class OrderUpdate(UpdateView):
    model = Order
    form_class = UpdateOrderForm
    permission_required = 'studio.can_mark_returned'

    def post(self, request, *args, **kwargs):
        print(request)
        return super().post(request, *args, **kwargs)


class OrderUserDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('my-order')

    def get(self, request, *args, **kwargs):
        if self.get_object().status == 'n':
            return super().get(request, *args, **kwargs)
        return redirect('my-order')


class OrderAdminDelete(PermissionRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('all-order')
    permission_required = 'studio.can_mark_returned'


class StudioLoginView(LoginView):
    template_name = 'registrations/login.html'


class StudioLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'registrations/login.html'


class RegisterUserView(CreateView):
    model = User
    template_name = 'registration/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('index')

# class RegisterDoneView(TemplateView):
#     template_name = 'registration/register_done.html'

portal/studio/templates/studio/order_confirm_delete.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/style.css' %}">
    <title>Design Pro</title>
</head>
<div class="form_login">
    <div class="login_text">
            <h1>Удалить заказ</h1>
        <p>Вы уверены, что хотите удалить заказ: {{ order }}?</p>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" id="submit" action="" value="Да, удалить.">
    </form>
</div>
<footer>
    <p>&copy; Все права защищены</p>
</footer>
</body>
</html>

portal/studio/templates/studio/order_detail.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/style.css' %}">
    <title>Design Pro</title>
</head>
<body>
<div class="mein">
    <div class="content">
        <h1>Заказ: {{ order.name }}</h1>
        <div class="project">
            <div class="info">
                <p><strong>Время создания:</strong> {{ order.day_add}}</p>
                <p><strong>Заказчик:</strong> {{ order.customer_order}}</p>
                <p><strong>Описание:</strong> {{ order.summary }}</p>
                <p><strong>Категория:</strong> {{ order.category }}</p>
                <p><strong>Статус:</strong> {{ order.get_status_name }}</p>
                <p class="strong_p"><strong class="strong">Фото:</strong> <img src="{% thumbnail order.photo_file 'index' %}"></p>
                {% if order.status == 'a' %}
                <p><strong>Коментарий:</strong> {{ order.comment }}</p>
                {% endif %}
                {% if order.status == 'c' %}
                <p class="strong_p"><strong class="strong">Результат:</strong> <img src="{% thumbnail order.img 'index' %}"></p>
                {% endif %}
                {% if order.status != 'a' and order.status != 'c' %}
                <div class="link">
                    <a href="{% url 'order-delete' order.pk %}">Удалить заказ</a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="link">
            <a href="{% url 'index'  %}">Главная</a>
        </div>
    </div>
</div>
<footer>
    <p>&copy; Все права защищены</p>
</footer>
</body>
</html>

portal/studio/templates/studio/order_form.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/style.css' %}">
    <title>Design Pro</title>
</head>
<body>
<div class="form_login">
    {% if not user.is_staff %}
        <div class="login_text">
        <h2>Создание заказа</h2>
    </div>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="name" id="id_name" placeholder="Название" required>
        <input type="text" name="summary" id="id_summary" placeholder="Описание" required>
        <span>Выбор категории</span>
        <select name="category" id="id_category">
            <option value selected>---------</option>
            <option value="1">Эскиз</option>
            <option value="2">Конструктор</option>
        </select><br>
        <input type="file" name="photo_file" id="image" accept="image/*">
        <input type="submit" id="submit" value="Создать">
        <input type="hidden" name="next" value="next">
    </form>
    {% endif %}
    {% if perms.studio.can_mark_returned %}
            <div class="login_text">
        <h2>Обновление заказа</h2>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {% for field in form %}
            <div class="input">
                {{ field.errors }}
                <br>{{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                {% endif %}
            </div>
            {% endfor %}
        </table>
        <br>
        <input type="submit" id="submit" value="Обновить">
        <input type="hidden" name="next" value="next">
        <div class="link_filter">
            <a href="{% url 'index'  %}">Главная</a>
        </div>
    </form>
    {% endif %}
</div>
<footer>
    <p>&copy; Все права защищены</p>
</footer>
</body>
</html>

portal/studio/templates/studio/order_list_customer_all.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/style.css' %}">
    <title>Design Pro</title>
</head>
<body>
<div class="order_list">
    <div class="mein">
        <div class="link">
            <a href="{% url 'index'  %}">Главная</a>
            <a href="{% url 'all-order' %}">Все заказы</a>
            <a href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
        </div>
        <div class="content">
            <h1>Ваши заказы</h1>
            {% if order_list %}
            {% for order in order_list %}
            <div class="project">
                <div class="link_list">
                    <img src="{% thumbnail order.photo_file 'index' %}" alt="Картинка">
                    <a href="{% url 'order-detail' order.pk %}">{{order.name}}</a> {% if user.is_staff %}- Заказчик:{{ order.customer_order }}
                    <div class="link_list">Статус: {{ order.get_status_name }} {% endif %} {% if perms.studio.can_mark_returned %}- <a
                            href="{% url 'order-update' order.id %}">Обновить статус</a></div>
                    {% endif %}
                </div>
            </div>
            <br>
            {% endfor %}
            {% else %}
            <p>Заказов нет</p>
            {% endif %}
        </div>
    </div>
</div>
<footer>
    <p>&copy; Все права защищены</p>
</footer>
</body>
</html>

portal/studio/templates/studio/order_list_customer_user.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/style.css' %}">
    <title>Design Pro</title>
</head>
<div class="order_list">
    <div class="mein">
        <div class="link">
            <a href="{% url 'index'  %}">Главная</a>
            <a href="{% url 'my-order' %}">Мои заказы</a>
            <a href="{% url 'order-create' %}">Создать заказ</a>
            <a href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
        </div>
        <div class="content">
            <h1>Мои заказы</h1>
                {% if order_list %}
                {% for order in order_list %}
                <div class="project">
                    <div class="link_list">
                        <img src="{% thumbnail order.photo_file 'index' %}" alt="Картинка">
                        <a href="{% url 'order-detail' order.pk %}">{{order.name}} </a>
                        <div><span class="font-weight-bold">Статус:</span> {{order.get_status_name}}</div>
                        <br>
                    </div>
                </div>
                <br>
                {% endfor %}
                {% else %}
                <p>Заказов нет</p>
                {% endif %}
        </div>
    </div>
    <footer>
        <p>&copy; Все права защищены</p>
    </footer>
    </body>
</div>
</html>